### ISSUE TITLE
Set active states for menu links

### ISSUE THREAD

**Issue by mitchellslager** [mitchellslager/portfolio-react#5]
When navigating to a page the correct menu link should be 'active'.
This should be easy by assigning a CSS class like:
````css
.active {
  color: #000;
}
````
However I don't know (yet) how I can assign this class when the route changes.
